% -------------------------------------------------------------------
%  Generated by MATLAB on 9-Oct-2018 20:21:58
%  MATLAB version: 9.5.0.944444 (R2018b)
% -------------------------------------------------------------------
saveVarsMat = load('ann1.mat');

n1 = saveVarsMat.n1; % <1x1 nnet.cnn.LayerGraph> unsupported class

clear saveVarsMat;
